#!/bin/python

from argparse import ArgumentParser
from pathlib import Path
from subprocess import run
from os import makedirs

epilog='''Packages are just configuration files of a program collected in a git repository,
this program is just a wrapper around git to help out.
See "git bare" dotfile management and stow to see what inspired this program'''

parser = ArgumentParser(description='Package tracker', epilog=epilog)
parser.add_argument('package', help='Package to work on')
parser.add_argument('--config_home', default=Path.home(), type=Path, help='Directory to search packages')
parser.add_argument('--work_tree', default=Path('/'), type=Path, help='Git working tree, default is /')
parser.add_argument('--create', action='store_true', help='Create package')

subparsers = parser.add_subparsers()
stat_parser = subparsers.add_parser('stat', help='file metadata operations')
stat_parser.add_argument('operation', choices=['save', 'apply'], help='save stats or apply saved stats to tracked files')

args, git_args = parser.parse_known_args()

package_path = f'{args.config_home}/{args.package}'
if args.create:
    makedirs(package_path, exist_ok=True)
    run('git init --bare', cwd=package_path, shell=True)
    run('git config --local status.showUntrackedFiles no', cwd=package_path, shell=True)
    exit(0)

if args.operation:
    if args.operation == 'save':
        print('save')
    if args.operation == 'apply':
        print('apply')
else:
    print('else')
    run(['git', f'--work-tree={args.work_tree}', f'--git-dir={package_path}', *git_args])
